name: Create and publish a Docker image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
        description: Name of the image
      context_path:
        required: true
        type: string
        description: Direcotry to Dockerfile
      version:
        required: false
        type: string
        default: latest
        description: Version of the application
      extra_labels:
        required: false
        type: string
        default: ""
        description: Custom labels to apply

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Login to GitHub Container Registry
        id: login
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@030e881283bb7a6894de51c315a6bfe6a94e05cf # v6
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ inputs.image_name }}
          tags: |
            type=raw,value=${{ inputs.version }}
            type=raw,value=latest
          labels: |
            org.opencontainers.image.version=${{ inputs.version }}
            ${{ inputs.extra_labels }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@bcafcacb16a39f128d818304e6c9c0c18556b85f # v7
        with:
          context: ${{ inputs.context_path }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ inputs.version }}

      # This step generates an artifact attestation for the image, which is an unforgeable statement about where and how it was built. It increases supply chain security for people who consume the image. For more information, see [Using artifact attestations to establish provenance for builds](/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds).
      - name: Attest
        id: attest
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ inputs.image_name}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
